### ISSUE TITLE
Transparent GameObjects Inside Transparent GameObjects are not Drawn

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeoengine#24]
I don't current have a code sample to post - sorry. But when I place a transparent GameObject inside another transparent GameObject, the interior GameObject is not drawn at all. Using BoxGeometry.

The goal is to have a fully transparent voxel container for picking but also use as a cursor where the interior cursor shape is not fully opaque.

**Comment by xeolabs** [comment]
Unfortunately you need to ensure that inner transparent box renders **before** the outer transparent box, so that the inner box's pixels are in the color and depth buffers before the outer box's. 

To achieve that, you need to attach a [Layer](http://xeoengine.org/docs/classes/Layer.html) to each box, with the inner box's Layer having a lower value for its ````priority```` property than the outer.

Layering of transparencies for this case is hard to do automatically on WebGL - if interested, see also this [article for SceneJS transparency](http://xeolabs.com/articles/scenejs-transparency/), which describes the problem in more detail for SceneJS. 

I think the Layer component should work OK for your case, though.

This is a good question for a FAQ, so I'll start that [here](https://github.com/xeolabs/xeoengine/wiki/FAQ) and build it up later.

**Comment by philmaker1** [comment]
OK, I'll try it again with a Layer. You have created plenty of awesome docs and examples and I will look at them again.

**Comment by philmaker1** [comment]
BTW, the layer worked great and so I will close this issue. Woot!
