### ISSUE TITLE
X-Frame-Options Error with Online Examples

### ISSUE THREAD

**Issue by philmaker1** [xeolabs/xeoengine#31]
The examples online don't seem to load on Chrome OS/Chromebook.

Refused to display 'http://xeoengine.org/examples/animation_CameraFlight_Entity.html' in a frame because it set 'X-Frame-Options' to 'DENY'.

BTW, the san-serif font for the examples page looks nice.

**Comment by xeolabs** [comment]
Yeah GitHub added X-Frame-Options to HTTP headers on GitHub pages last night, without warning. Broke SceneJS and THREE.js examples and documentation as well. 

So the examples browsers for all those frameworks need to be redesigned to not rely on iframes.  If you have any ideas on that, please let us know, would be a priority item.

THREE has this issue [logged here](https://github.com/mrdoob/three.js/issues/7955), so we can also see what their community comes up with. And if we get any ideas, would be good to suggest them over there as well (xeoEngine and SceneJS example gallery browser is based on the THREE one after all, would be good to send some love back!).

In the meantime, here's a note on how to massage URLs to xeoEngine and Scene examples gallery links so they resolve directly, instead of via the example pages (and their iframes): 

https://github.com/xeolabs/scenejs/wiki/Accessing-examples-broken-by-new-GitHub-X-Frame-Options

**Comment by xeolabs** [comment]
Probably a server update with that option inadvertently left as default. That broke a lot of sites today. My money is on GitHub fixing that by itself. [Happened before](https://twitter.com/mbostock/status/257933324406882304) and they fixed.  Let's wait and see what happens.

**Comment by xeolabs** [comment]
Looks like GitHub fixed this.
