### ISSUE TITLE
Collection causes error when using it with a scene

### ISSUE THREAD

**Issue by quaxquax** [xeolabs/xeoengine#35]
[LK: This is actually related to https://github.com/xeolabs/xeoengine/issues/36]

Seem to have stumbled onto another bug.  Same fiddle as before https://jsfiddle.net/quaxquax/pb2Ls5s2/

When adding a definition for a Collection it goes dark, and throws an "unreachable code after return statement" on the browser console.

Uncommenting the line 25 that contains 'var myCollections = new XEO.Collection();' makes everything whole again.

**Comment by xeolabs** [comment]
Aha yes this would be due to having two scenes, both trying to create their default canvases within the same page. 

So when you've already created your own Scene, then create the XEO.Collection without specifying a Scene for it, then the Collection will fall back on the default Scene (which XEO lazy-creates only at that point).

For such cases, I need to make XEO lay the canvases out in a flow layout, so that they don't clash with each other like that. The other complication is that XEO also creates overlay DIVs over those canvases, as part of the way it captures user input events.

These are a couple of edge-cases I need to think through properly. For now, don't use the default Scene alongside your own Scene(s). Great that you've highlighted that issue before the first release actually.

**Comment by quaxquax** [comment]
Thanks for clearing this up for me. 

Indeed, using XEO.Collection(myScene) works just fine.
