### ISSUE TITLE
Textures need to be flipped on Y-axis in XEO.Model

### ISSUE THREAD

**Issue by cx20** [xeolabs/xeoengine#44]
I tried latest xeoEngine glTF loader (Built on 2016-01-29).
But, I have noticed that the texture of the duck is funny.
Probably I think the texture is turned upside down.

http://jsdo.it/cx20/4rxr
https://github.com/KhronosGroup/glTF/tree/master/sampleModels/duck/glTF

**Comment by xeolabs** [comment]
Yes it will need to be flipped - thanks, will fix on the weekend.

**Comment by xeolabs** [comment]
Fixed in https://github.com/xeolabs/xeoengine/commit/0642affe56a0f06d5499e57655eba05e4fd1f4ba and https://github.com/xeolabs/xeoengine/commit/e7db6f460b0e17338fdd1e55d84e360536ad77f4

gl.UNPACK_FLIP_Y_WEBGL is false by default in WebGL, however needs to be set true for glTF, so I added the ````flipY```` parameter to ````XEO.Texture````.

* [glTF Duck example](http://xeoengine.org/examples/importing_gltf_duck.html)
* [flipY in API docs](http://xeoengine.org/docs/classes/Texture.html#property_flipY)

**Comment by cx20** [comment]
Thanks!

I have confirmed that it has been fixed.
http://jsdo.it/cx20/a9Ga
